name: CustomTagSystem
version: '${project.version}'
main: org.customTagSystem.CustomTagSystem
api-version: '1.20'
depend: [Vault]
softdepend: [PlaceholderAPI]
author: CustomTagSystem
description: Sistema completo de tags personalizados

commands:
  tags:
    description: Abre el menú de tags
    usage: /tags [reload]
    aliases: [tag]

permissions:
  tags.use:
    description: Permite usar el comando /tags
    default: true
  tags.reload:
    description: Permite recargar la configuración
    default: op